version: '3.4'

services:
  seed:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - NODE_ADDRESS=^10.0.*.*
    networks:
      - galera_network
    command: seed
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - xtrabackup_password
      - mysql_password
      - mysql_root_password
  node:
    image: colinmollenhour/mariadb-galera-swarm
    environment:
      - XTRABACKUP_PASSWORD_FILE=/run/secrets/xtrabackup_password
      - NODE_ADDRESS=^10.0.*.*
      - HEALTHY_WHILE_BOOTING=1
    networks:
      - galera_network
    command: node tasks.seed,tasks.node
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1
    secrets:
      - xtrabackup_password
  nextcloud:
    image: nextcloud
    environment:
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_HOST=node
    networks:
      - galera_network
    volumes:
      - nextcloud_data:/var/www/html
    ports:
      - "8080:80"
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus_data
      - --storage.tsdb.retention.time=90d
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data:/prometheus_data
    networks:
      - galera_network
    configs:
      - source: geco-prometheus
        target: /etc/prometheus/prometheus.yml # On remonte la config crée plus haut dans le container.
    deploy:
      placement:
        constraints:
          - node.role == manager
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - galera_network
    depends_on:
      - prometheus
  exporter:
    image: xperimental/nextcloud-exporter:latest
    environment:
      - NEXTCLOUD_SERVERINFO_URL=http://nextcloud/ocs/v2.php/apps/serverinfo/api/v1/info
    ports:
      - 8081:8081
    volumes:
      - ./exporteur/nextcloud_exporter_data/config.yml:/conf:ro
    networks:
      - galera_network
    depends_on:
      - prometheus

volumes:
  mysql-data:
    name: '{{.Service.Name}}-{{.Task.Slot}}-data'
    driver: local
  nextcloud_data:
    driver: local
  prometheus_data:
    driver: local
  nextcloud_exporter_data:
    driver: local

networks:
  galera_network:
    driver: overlay

secrets:
  xtrabackup_password:
    file: .secrets/xtrabackup_password
  mysql_password:
    file: .secrets/mysql_password
  mysql_root_password:
    file: .secrets/mysql_root_password

configs:
  geco-prometheus:
    file: ./prometheus_data/prometheus.yml
