version: '3.4'

services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.swarm.network=traefik_network"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.http.tls.certresolver=myresolver"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.myresolver.acme.email=tsic@ensg.eu"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.reverse-proxy.rule=Host(`Traefik.ensg2025.duckdns.org`)"
        - "traefik.http.services.reverse-proxy.loadbalancer.server.port=8080"
networks:
  network:


volumes:
  letsencrypt:
    driver: local
