version: '3.4'

services:
  reverse-proxy:
    image: traefik:v3.3
    command: --api.insecure=true --providers.docker --providers.swarm.network=traefik_network
    ports:
      - "81:80"
      - "444:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network

networks:
  network: