services:
  onlyoffice-document-server:
    image: onlyoffice/documentserver:8.3.0
    environment:
      - JWT_SECRET=secret
    ports:
      - "8081:80"
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - frontend_network
      - traefik_network
    deploy:
      labels:
        - "traefik.docker.network=traefik_network"
        - "traefik.enable=true"
        - "traefik.http.routers.onlyoffice-document-server.rule=Host(`OO.ensg.duckdns.org.127.0.0.1.nip.io`)"
        - "traefik.http.routers.onlyoffice-document-server.tls.certresolver=myresolver"

volumes:
  document_data:
  document_log:

networks:
  frontend_network:
    driver: overlay
  traefik_network:
    external: true
