services:
  onlyoffice-document-server:
    image: onlyoffice/documentserver:8.3.0
    environment:
      - JWT_SECRET=secret
    ports:
      - "8081:80"
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - frontend_network

volumes:
  document_data:
  document_log:

networks:
  frontend_network:
    driver: overlay
