{
 "title": "Nextcloud Exporter Prometheus Dashboard",
 "description": "Dashboard for Nextcloud Prometheus data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Shared Links By Type",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nextcloud_shares_total{type=\"authlink\"}",
     "legendFormat": "authlink"
    },
    {
     "expr": "nextcloud_shares_total{type=\"link\"}",
     "legendFormat": "link"
    },
    {
     "expr": "nextcloud_shares_total{type=\"group\"}",
     "legendFormat": "group"
    },
    {
     "expr": "nextcloud_shares_total{type=\"user\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "Free Space Remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "nextcloud_free_space_bytes - 1099511627776"
    }
   ]
  },
  {
   "title": "PHP Max Upload File Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "nextcloud_php_upload_max_size_bytes"
    }
   ]
  },
  {
   "title": "App Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nextcloud_up" }
   ]
  },
  {
   "title": "PHP Max Memory Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "nextcloud_php_memory_limit_bytes"
    }
   ]
  },
  {
   "title": "Current Active Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nextcloud_active_users_total" }
   ]
  },
  {
   "title": "Federated Nextcloud Data Exchange Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nextcloud_shares_federated_total{direction=\"received\"}",
     "legendFormat": "recieved"
    },
    {
     "expr": "nextcloud_shares_federated_total{direction=\"sent\"}",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 6 },
   "targets": [
    { "expr": "nextcloud_database_size_bytes" }
   ]
  },
  {
   "title": "Total Authorization Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nextcloud_auth_errors_total" }
   ]
  },
  {
   "title": "Total File Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nextcloud_files_total" }
   ]
  }
 ]
}