services:
  nextcloud:
    image: nextcloud
    ports:
      - "8084:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=formation20242025
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_HOST=node
    networks:
      - onlyoffice_frontend_network
      - galera_backend_network
      - traefik_network
    deploy:
      labels:
        - "traefik.docker.network=traefik_network"
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.rule=Host(`NC.ensg.duckdns.org.127.0.0.1.nip.io`)"
        - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"

volumes:
  nextcloud_data:
    driver: local

networks:
  onlyoffice_frontend_network:
    external: true
  galera_backend_network:
    external: true
  traefik_network:
    external: true
