version: '3.4'

services:
  nextcloud:
    container_name: app-server
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=formation20242025
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_HOST=node
    networks:
      - frontend_network
      - backend_network

volumes:
  nextcloud_data:
    driver: local

networks:
  frontend_network:
    external: true
  backend_network:
    external: true
