# # required
# server: "https://nextcloud:80"
# # required for token authentication
# username: "admin"
# password: "admin"
# # optional
# listenAddress: "nextcloud:80"
# timeout: "5s"
# tlsSkipVerify: false